### ISSUE TITLE
Storm stability issue

### ISSUE THREAD

**Issue by mattburns** [KasperMadsen/storm-deploy-alternative#16]
Firstly, storm-deploy-alternative is awesome, thanks!

It works great for me and I run a simple 2-node cluster:
```
stormcluster:
    - storm-version "0.9.5"					# Version of Storm
    - zk-version "3.4.6"					# Version of Zookeeper
    - image "us-east-1/ami-d726abbe"		# Ubuntu 14.04 LTS AMI
    - region "us-east-1"					# Region
    - m3.large {ZK, WORKER, MASTER, UI, LOGVIEWER}	# Request service
    - m3.large {ZK, WORKER, LOGVIEWER}				# Request service
    - remote-exec-preconfig {cd ~, echo hey > hey.txt, sudo apt-get -y install libimage-exiftool-perl}
    - remote-exec-postconfig {}
```

However, it generally runs my web-crawling topology fine for a couple of days and then everything just stops. This is all I can see on the storm-ui. Any ideas where I should start looking?

**Storm UI**
**Cluster Summary**
**Topology summary**
**Supervisor summary**
**Nimbus Configuration**
**Internal Server Error**
```
org.apache.thrift7.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
	at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
	at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
	at backtype.storm.ui.core$cluster_configuration.invoke(core.clj:472)
	at backtype.storm.ui.core$fn__6088.invoke(core.clj:844)
	at compojure.core$make_route$fn__4275.invoke(core.clj:93)
	at compojure.core$if_route$fn__4263.invoke(core.clj:39)
	at compojure.core$if_method$fn__4256.invoke(core.clj:24)
	at compojure.core$routing$fn__4281.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2443)
	at compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:619)
	at compojure.core$routes$fn__4285.invoke(core.clj:111)
	at ring.middleware.reload$wrap_reload$fn__4310.invoke(reload.clj:14)
	at backtype.storm.ui.core$catch_errors$fn__6135.invoke(core.clj:909)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__4952.invoke(keyword_params.clj:27)
	at ring.middleware.nested_params$wrap_nested_params$fn__4991.invoke(nested_params.clj:65)
	at ring.middleware.params$wrap_params$fn__4924.invoke(params.clj:55)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__5019.invoke(multipart_params.clj:103)
	at ring.middleware.flash$wrap_flash$fn__5200.invoke(flash.clj:14)
	at ring.middleware.session$wrap_session$fn__5189.invoke(session.clj:43)
	at ring.middleware.cookies$wrap_cookies$fn__5120.invoke(cookies.clj:160)
	at ring.adapter.jetty$proxy_handler$fn__5400.invoke(jetty.clj:16)
	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
	... 33 more

```

**Comment by KasperMadsen** [comment]
Hi there,
Thank you for your kind words. 

Your problem is not related to the deployment tool, which once executed has no impact on the software executed on the instances. Based on your logs, I would guess that you have a misconfiguration in your Storm topology. I suggest you to monitor memory, cpu, swap and so on using Ganglia, which is already installed by the deployment tool. This will most likely give you insight into why you are experiencing problems.

**Comment by mattburns** [comment]
Ahh, thanks for the tip. Ganglia pointed out to me that the root partition was full!

It's only 10GB and ~7GB of it was zookeeper logs:

9796040	/
6745500	/tmp
6741288	/tmp/zktmp
6741276	/tmp/zktmp/version-2
1687284	/home
1687280	/home/ubuntu
1597080	/home/ubuntu/storm
1574012	/home/ubuntu/storm/logs
727528	/usr
508804	/var

Once I deleted (`rm -rf  /tmp/zktmp/version-2/log.1000*`) those offending logs everything seems to spin back to life...

I'll have a read about zookeeper and see what I can do to limit the logs. Thanks for your help.

**Comment by KasperMadsen** [comment]
Glad I could help :+1:
