### ISSUE TITLE
could not get imageId

### ISSUE THREAD

**Issue by timmolter** [KasperMadsen/storm-deploy-alternative#17]
Any idea what the problem could be? It could very well be that I don't have my AWS account setup correctly. I'm not 100% sure what I need to have setup on AWS.

    2015-12-18 14:57:26 [INFO] Starting 1 instance(s) of type t2.micro with daemons [WORKER]
    2015-12-18 14:57:26 [INFO] Starting 1 instance of type t2.micro with daemons [ZK, WORKER, MASTER, UI]
    2015-12-18 14:57:26 [ERROR] Problem: 
    java.util.NoSuchElementException: could not get imageId(us-west-2b/ami-76a49f2f)

**Comment by KasperMadsen** [comment]
I just did a search on AWS and your specified ami does not exist in the public repo. Are you using a private image? and if so, do you have permissions to access it from the account you are using to deploy?

**Comment by timmolter** [comment]
@KasperMadsen Thanks for the quick response. Yes it's private. Maybe I should switch it to public. 

I'm new to AWS so I'm not 100% sure I have the right permissions. If you know of a detailed guide on how to do that, it'd be appreciated. I'll look into it more....

**Comment by KasperMadsen** [comment]
I have been using private images without any problems, so as long as your have the needed permissions, it should work just fine :)

**Comment by timmolter** [comment]
@KasperMadsen I still cannot get this to work. Just a few sanity check questions:

1. I run your app from my local dev machine, right?
1. Do I need any public-private keys setup in some way?

**Comment by KasperMadsen** [comment]
1. Yes
2. You need ssh keys, but you will receive a warning if these are missing.

I suggest you to try deploying to a public image. If that works, then you know it is a problem with the private image.

**Comment by timmolter** [comment]
Strange. Deploying it when it's public doesn't work either. Here's my config. the AMI is set to public.

    #
    # Amazon EC2 example cluster configuration
    #
    ectwo:
        - storm-version "0.9.3"					# Version of Storm
        - zk-version "3.4.6"					# Version of Zookeeper
        - image "us-west-2a/ami-03100e62"		# Ubuntu 14.04 LTS AMI
        - region "us-west-2a"					# Region
        - t2.micro {ZK, WORKER, MASTER, UI}		# Request service
        - t2.micro {WORKER}					# Request service
        - remote-exec-preconfig {cd ~, echo hey > hey.txt}
        - remote-exec-postconfig {}

I don't have ssh keys setup, at least not for AWS. I haven't seen any errors about that. Isn't the `credential.yaml` file all that's needed? If not, what do I need to do with the ssh keys?

Thanks.

**Comment by KasperMadsen** [comment]
Please try the example in the frontpage of the project (here on github). Let me know if that works.

**Comment by timmolter** [comment]
Well, I got further? 

java.lang.IllegalArgumentException: DER length more than 4 bytes: 32
		at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
		at org.jclouds.crypto.ASN1Codec.readLength(ASN1Codec.java:161)
		at org.jclouds.crypto.ASN1Codec.create(ASN1Codec.java:150)
		at org.jclouds.crypto.ASN1Codec.createASN1Sequence(ASN1Codec.java:84)
		at org.jclouds.crypto.ASN1Codec.decodeRSAPrivateKey(ASN1Codec.java:64)
		at org.jclouds.crypto.Pems$DecodeRSAPrivateCrtKeySpec.parseResult(Pems.java:238)
		at org.jclouds.crypto.Pems$DecodeRSAPrivateCrtKeySpec.parseResult(Pems.java:233)
		at org.jclouds.crypto.Pems$PemProcessor.getResult(Pems.java:98)
		at com.google.common.io.ByteSource$ByteArrayByteSource.read(ByteSource.java:546)
		at org.jclouds.crypto.Pems.fromPem(Pems.java:195)
		at org.jclouds.crypto.Pems.privateKeySpec(Pems.java:214)
		at org.jclouds.crypto.Pems.privateKeySpec(Pems.java:252)
		at org.jclouds.ssh.SshKeys.fingerprintPrivateKey(SshKeys.java:211)
		at org.jclouds.ec2.domain.KeyPair$Builder.build(KeyPair.java:75)
		at org.jclouds.aws.ec2.compute.strategy.CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.createNewKeyPairUnlessUserSpecifiedOtherwise(CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.java:130)
		at org.jclouds.ec2.compute.strategy.CreateKeyPairAndSecurityGroupsAsNeededAndReturnRunOptions.execute(CreateKeyPairAndSecurityGroupsAsNeededAndReturnRunOptions.java:78)
		at org.jclouds.aws.ec2.compute.strategy.CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.execute(CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.java:79)
		at org.jclouds.aws.ec2.compute.strategy.CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.execute(CreateKeyPairPlacementAndSecurityGroupsAsNeededAndReturnRunOptions.java:50)
		at org.jclouds.ec2.compute.strategy.EC2CreateNodesInGroupThenAddToSet.createKeyPairAndSecurityGroupsAsNeededThenRunInstances(EC2CreateNodesInGroupThenAddToSet.java:213)
		at org.jclouds.ec2.compute.strategy.EC2CreateNodesInGroupThenAddToSet.runInstancesAndWarnOnInvisible(EC2CreateNodesInGroupThenAddToSet.java:151)
		at org.jclouds.ec2.compute.strategy.EC2CreateNodesInGroupThenAddToSet.execute(EC2CreateNodesInGroupThenAddToSet.java:132)
		at org.jclouds.compute.internal.BaseComputeService.createNodesInGroup(BaseComputeService.java:210)
		at org.jclouds.ec2.compute.EC2ComputeService.createNodesInGroup(EC2ComputeService.java:149)
		at dk.kaspergsm.stormdeploy.LaunchNodeThread.run(LaunchNodeThread.java:76)

**Comment by timmolter** [comment]
Looks like something with the CA cert. I did get a couple cert (.pem) files from AWS when I set things up, but I didn't do anything with them yet. Looking now...

**Comment by KasperMadsen** [comment]
You need to provide more information about what you are doing. Otherwise it is impossible for me to help you. Did you do what I suggested and tried the default deployment configuration as given in the github frontpage? You mention you got further, how? ... Did you solve the original problem and if so, how?

You do not need the pem files from AWS for deploying. What is the distro you are using, incl. Java, Javac and Maven?

**Comment by timmolter** [comment]
Sorry for not being clear. Yes, I tried your suggestion. I then got that exception above. Then I started looking into the code and saw that it looks for a private and public RSA key in `~/.ssh/id_rsa` and  `~/.ssh/id_rsa.pub`. So I figured it had something to do with that.

I then took the private key pem file from Amazon, converted it to a RSA format, and created a corresponding public RSA key file and put them in `~/.ssh/id_rsa` and  `~/.ssh/id_rsa.pub`. Then it worked!

So that leads me to two questions:

1) Is the better way to create you own priv/pub key pair and upload that to AWS, rather than the round-about way I did it? In other words, is that what you did?
2) Now that it's started and running (I can see the Storm UI and Ganglia) why don't I see the instances in my EC2 dashboard?

Next challenge is to get it to run with my own AMI on a `t2.micro` instance.

BTW, I'm using OSX 10.11.2, Java and Javac build 1.8.0_45-b14 and Maven 3.3.9.

**Comment by timmolter** [comment]
Update: The following config now works for me. The deployed instances show up in my EC2 dashboard as well now. I don't know why the other ones did not before, for the default config file given in your README file.

    #
    # Amazon EC2 example cluster configuration
    #
    ec4:
        - storm-version "0.9.3"					# Version of Storm
        - zk-version "3.4.6"					# Version of Zookeeper
        - image "us-west-2/ami-a9e2da99"		# Ubuntu 14.04 LTS AMI
        - region "us-west-2"					# Region
        - t2.micro {ZK, WORKER, MASTER, UI}		# Request service
        - t2.micro {WORKER}					# Request service
        - remote-exec-preconfig {cd ~, echo hey > hey.txt}
        - remote-exec-postconfig {}

It's interesting though to me that I needed to pick an AMI from here:<https://cloud-images.ubuntu.com/releases/14.04/release-20150609/>, and i couldn't find the one in the default config file given in your README file (ami-97344ae0) under AMIs on the EC2 dashboard. The original error I was getting (`could not get imageId`) was when I was trying to use an AMI I created in the EC2 dashboard, even if I made it public.

I still curious about the RSA keys too.

**Comment by timmolter** [comment]
I figured everything out. There were two important pieces of missing information that caused me to have major issues.

1. The supplied AMI needs to be an Ubuntu Amazon Cloud image. you can saerch for an appropriate one here: <https://cloud-images.ubuntu.com/locator/ec2/>
1. You need an SSH Key **with an empty passphrase** and it needs to be the `id_rsa` identify. Other than that all you need really are the `Access Key Id` and `Secret Access Key` info.

I submitted a PR so that non-default SSH Keys can be used, which is useful for dev machines with many SHH keys.

**Comment by KasperMadsen** [comment]
I am sorry you had so many issues. I am trying to make the software as simple as possible, and for most people it just works. Thanks for pointing out these issues to me. I will keep them in mind when making future updates.

Please note the following:
* With the default config, you start instances on eu-west-1. Please check your dashboard for that region, to see if you have ec2 instances running there!
* For the ssh keys, you do not need to use the ones provided by AWS. Your local one is automatically uploaded to AWS (see key pairs section in control panel).
