### ISSUE TITLE
Error while creating storm cluster

### ISSUE THREAD

**Issue by barkatdhillon** [KasperMadsen/storm-deploy-alternative#27]
I was creating/deploying storm cluster since 3 months with same configuration, but today I am getting following exception while creating storm cluster, last successfull I used on 14-feb-16.
[22:08:43][Step 2/3] Exception in thread "main" org.jclouds.rest.AuthorizationException: POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1 -> HTTP/1.1 401 Unauthorized
[22:08:43][Step 2/3] 	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.refineException(ParseAWSErrorFromXmlContent.java:122)
[22:08:43][Step 2/3] 	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:89)
[22:08:43][Step 2/3] 	at org.jclouds.http.handlers.DelegatingErrorHandler.handleError(DelegatingErrorHandler.java:65)
[22:08:43][Step 2/3] 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.shouldContinue(BaseHttpCommandExecutorService.java:136)
[22:08:43][Step 2/3] 	at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:105)
[22:08:43][Step 2/3] 	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
[22:08:43][Step 2/3] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
[22:08:43][Step 2/3] 	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
[22:08:43][Step 2/3] 	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
[22:08:43][Step 2/3] 	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
[22:08:43][Step 2/3] 	at com.sun.proxy.$Proxy61.describeRegions(Unknown Source)
[22:08:43][Step 2/3] 	at org.jclouds.ec2.suppliers.DescribeRegionsForRegionURIs.get(DescribeRegionsForRegionURIs.java:50)
[22:08:43][Step 2/3] 	at org.jclouds.ec2.suppliers.DescribeRegionsForRegionURIs.get(DescribeRegionsForRegionURIs.java:38)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
[22:08:43][Step 2/3] 	at org.jclouds.location.suppliers.derived.RegionIdsFromRegionIdToURIKeySet.get(RegionIdsFromRegionIdToURIKeySet.java:45)
[22:08:43][Step 2/3] 	at org.jclouds.location.suppliers.derived.RegionIdsFromRegionIdToURIKeySet.get(RegionIdsFromRegionIdToURIKeySet.java:33)
[22:08:43][Step 2/3] 	at com.google.common.base.Suppliers$SupplierComposition.get(Suppliers.java:67)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[22:08:43][Step 2/3] 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[22:08:43][Step 2/3] 	at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
[22:08:43][Step 2/3] 	at org.jclouds.aws.ec2.compute.strategy.AWSEC2ListNodesStrategy.pollRunningInstances(AWSEC2ListNodesStrategy.java:65)
[22:08:43][Step 2/3] 	at org.jclouds.ec2.compute.strategy.EC2ListNodesStrategy.listDetailsOnNodesMatching(EC2ListNodesStrategy.java:107)
[22:08:43][Step 2/3] 	at org.jclouds.ec2.compute.strategy.EC2ListNodesStrategy.listNodes(EC2ListNodesStrategy.java:86)
[22:08:43][Step 2/3] 	at org.jclouds.ec2.compute.strategy.EC2ListNodesStrategy.listNodes(EC2ListNodesStrategy.java:58)
[22:08:43][Step 2/3] 	at org.jclouds.compute.internal.BaseComputeService.listNodes(BaseComputeService.java:335)
[22:08:43][Step 2/3] 	at dk.kaspergsm.stormdeploy.commands.Deploy.deploy(Deploy.java:44)
[22:08:43][Step 2/3] 	at dk.kaspergsm.stormdeploy.StormDeployAlternative.main(StormDeployAlternative.java:81)
[22:08:43][Step 2/3] Caused by: org.jclouds.http.HttpResponseException: request: POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1  [Action=DescribeRegions] failed with response: HTTP/1.1 401 Unauthorized
[22:08:43][Step 2/3] 	at org.jclouds.aws.handlers.ParseAWSErrorFromXmlContent.handleError(ParseAWSErrorFromXmlContent.java:63)
[22:08:43][Step 2/3] 	... 41 more
[22:08:43][Step 2/3] Process exited with code 1

**Comment by KasperMadsen** [comment]
I have reproduced the problem. I will look into it over the next few days. I suspect one of the following scenarios:

1. AWS have tightened the security and requires SSL communication with newer version of protocol
2. Intermittent problem

**Comment by KasperMadsen** [comment]
I solved my problem by recreating my ec2 credentials. Please try and report back if that solves your problem. I also implemented a sanity check for credentials, which checks there are no spaces at the start or end.

**Comment by barkatdhillon** [comment]
I just cloned your latest repository and recreated new access keys, but still got the same error.

**Comment by KasperMadsen** [comment]
It works fine for me. Are you using IAM access keys? ... If so, try administrator access keys instead to check if it is a permission problem with your keys.

**Comment by KasperMadsen** [comment]
Is your problem solved?

**Comment by barkatdhillon** [comment]
No, I tried with root access key with your latest code, but still same issue.

**Comment by KasperMadsen** [comment]
That is too bad :| ... It is almost impossible for me to debug, since I cannot replicate the problem.

**Comment by barkatdhillon** [comment]
When I used other machine and root credentials, then it worked fine. I think we can close this issue.
