### ISSUE TITLE
Could not find leader Nimbus from seed hosts

### ISSUE THREAD

**Issue by ndtreviv** [KasperMadsen/storm-deploy-alternative#46]
When I attempt to deploy a 2-node cluster, Storm UI comes up with this error on the main page:
```
org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts ["54.91.82.190"]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.ui.core$all_topologies_summary.invoke(core.clj:433)
	at org.apache.storm.ui.core$fn__12498.invoke(core.clj:951)
	at org.apache.storm.shade.compojure.core$make_route$fn__4604.invoke(core.clj:93)
	at org.apache.storm.shade.compojure.core$if_route$fn__4592.invoke(core.clj:39)
	at org.apache.storm.shade.compojure.core$if_method$fn__4585.invoke(core.clj:24)
	at org.apache.storm.shade.compojure.core$routing$fn__4610.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2570)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at org.apache.storm.shade.compojure.core$routes$fn__4614.invoke(core.clj:111)
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__11958.invoke(json.clj:56)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__5680.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__11140.invoke(reload.clj:22)
	at org.apache.storm.ui.helpers$requests_middleware$fn__5907.invoke(helpers.clj:46)
	at org.apache.storm.ui.core$catch_errors$fn__12679.invoke(core.clj:1224)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__5611.invoke(keyword_params.clj:27)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__5651.invoke(nested_params.clj:65)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__5582.invoke(params.clj:55)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__5680.invoke(multipart_params.clj:103)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__5866.invoke(flash.clj:14)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__5854.invoke(session.clj:43)
	at org.apache.storm.shade.ring.middleware.cookies$wrap_cookies$fn__5782.invoke(cookies.clj:160)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__5488.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__5492.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

The config I am using:
```
stormcluster-phasher-2x:
    - m3.2xlarge {ZK, WORKER, MASTER, UI}
    - m3.2xlarge {WORKER}
    - storm-version "1.0.1"
    - zk-version "3.4.8"
    - image "us-east-1/ami-038f5168"		#Ubuntu 14.04 LTS AMI
    - region "us-east-1"
    - m3.2xlarge {ZK, WORKER, MASTER, UI, LOGVIEWER}
    - remote-exec-preconfig {cd ~, sudo apt-get -y install libimage-exiftool-perl python-pip python-dev, sudo pip install awscli, sudo mkdir /mnt/urls, sudo chown ubuntu /mnt/urls}
    - remote-exec-postconfig {}
    - install-dir "/mnt/storm"
    - zk-data-dir "/mnt/zkdata"
    - zk-retain-snapshots "3"
    - zk-purge-interval "6"
```

Local `storm.yaml`:
```
storm.zookeeper.servers:
    - "54.91.82.190"
    - "54.91.255.175"
nimbus.seeds: ["54.91.82.190"]
ui.host: "54.91.82.190"
cluster: "stormcluster-phasher-2x"
```

Local `supervisor.yaml`:
```
storm.supervisor.servers:
    - "54.91.82.190"
    - "54.167.87.59"
    - "54.91.255.175"
```
Not sure why there are three when it's a 2-node cluster?

Remote `storm.yaml`
```
nimbus.seeds: [54.91.82.190]
storm.zookeeper.servers:
- 10.178.74.30
- 10.183.80.152
supervisor.scheduler.meta:
  instancetype: "m3.2xlarge"
```

Interestingly, when I deploy a one-node cluster and attempt to scale it out by one more (adding a worker), the worker is never picked up by the master either.

I'm going to investigate why this is happening, but if anyone else has any ideas...?

I'll record findings here in case others experience the same problems.

**Comment by ndtreviv** [comment]
Actually, I can see my config is wrong. I have incorrectly identified two MASTERs.

However, now when I correct this I get:
```
2016-09-20 11:57:54 [ERROR] Command not considered safe to retry because request method is POST: [method=org.jclouds.ec2.features.AvailabilityZoneAndRegionApi.public abstract java.util.Set org.jclouds.ec2.features.AvailabilityZoneAndRegionApi.describeAvailabilityZonesInRegion(java.lang.String,org.jclouds.ec2.options.DescribeAvailabilityZonesOptions[])[us-east-1, [Lorg.jclouds.ec2.options.DescribeAvailabilityZonesOptions;@11653972], request=POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1]
Exception in thread "main" org.jclouds.http.HttpResponseException: Unexpected end of file from server connecting to POST https://ec2.us-east-1.amazonaws.com/ HTTP/1.1
        at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:117)
        at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
        at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
        at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
        at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
        at com.sun.proxy.$Proxy60.describeAvailabilityZonesInRegion(Unknown Source)
        at org.jclouds.ec2.suppliers.DescribeAvailabilityZonesInRegion.get(DescribeAvailabilityZonesInRegion.java:52)
        at org.jclouds.ec2.suppliers.DescribeAvailabilityZonesInRegion.get(DescribeAvailabilityZonesInRegion.java:36)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
        at org.jclouds.location.suppliers.derived.ZoneIdsFromRegionIdToZoneIdsValues.get(ZoneIdsFromRegionIdToZoneIdsValues.java:43)
        at org.jclouds.location.suppliers.derived.ZoneIdsFromRegionIdToZoneIdsValues.get(ZoneIdsFromRegionIdToZoneIdsValues.java:31)
        at com.google.common.base.Suppliers$SupplierComposition.get(Suppliers.java:67)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
        at org.jclouds.location.suppliers.all.ZoneToRegionToProviderOrJustProvider.get(ZoneToRegionToProviderOrJustProvider.java:72)
        at org.jclouds.location.suppliers.all.ZoneToRegionToProviderOrJustProvider.get(ZoneToRegionToProviderOrJustProvider.java:46)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:73)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier$SetAndThrowAuthorizationExceptionSupplierBackedLoader.load(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:57)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
        at org.jclouds.rest.suppliers.MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.get(MemoizedRetryOnTimeOutButNotOnAuthorizationExceptionSupplier.java:119)
        at org.jclouds.ec2.compute.functions.RunningInstanceToNodeMetadata.findLocationWithId(RunningInstanceToNodeMetadata.java:238)
        at org.jclouds.ec2.compute.functions.RunningInstanceToNodeMetadata.getLocationForAvailabilityZoneOrRegion(RunningInstanceToNodeMetadata.java:228)
        at org.jclouds.ec2.compute.functions.RunningInstanceToNodeMetadata.apply(RunningInstanceToNodeMetadata.java:126)
        at org.jclouds.ec2.compute.functions.RunningInstanceToNodeMetadata.apply(RunningInstanceToNodeMetadata.java:69)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:314)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:300)
        at org.jclouds.ec2.compute.strategy.EC2ListNodesStrategy.listDetailsOnNodesMatching(EC2ListNodesStrategy.java:110)
        at org.jclouds.ec2.compute.strategy.EC2ListNodesStrategy.listDetailsOnNodesMatching(EC2ListNodesStrategy.java:58)
        at org.jclouds.compute.internal.BaseComputeService.detailsOnAllNodes(BaseComputeService.java:684)
        at org.jclouds.compute.internal.BaseComputeService.nodesMatchingFilterAndNotTerminated(BaseComputeService.java:314)
        at org.jclouds.compute.internal.BaseComputeService.nodesMatchingFilterAndNotTerminatedExceptionIfNotFound(BaseComputeService.java:323)
        at org.jclouds.compute.internal.BaseComputeService.runScriptOnNodesMatching(BaseComputeService.java:579)
        at dk.kaspergsm.stormdeploy.Tools.executeOnNodes(Tools.java:121)
        at dk.kaspergsm.stormdeploy.commands.Deploy.deploy(Deploy.java:86)
        at dk.kaspergsm.stormdeploy.StormDeployAlternative.main(StormDeployAlternative.java:75)
```

**Comment by ndtreviv** [comment]
Can't reproduce this, so must have just been my idiocy with the config.

**Comment by swapnilkumbhar1602** [comment]
DEBUG o.a.s.s.resource.ResourceUtils - Unable to extract resource requirement for Component SpoutSpec(spout_object:<ComponentObject serialized_java:AC ED 00 05 73 72 00 09 57 6F 72 64 53 70 6F 75 74 5D 5C C3 23 8C 4B 40 80 02 00 02 5A 00 0D 69 73 44 69 73 74 72 69 62 75 74 65 64 4C 00 09 63 6F 6C 6C 65 63 74 6F 72 74 00 2D 4C 6F 72 67 2F 61 70 61 63 68 65 2F 73 74 6F 72 6D 2F 73 70 6F 75 74 2F 53 70 6F 75 74 4F 75 74 70 75 74 43 6F 6C 6C 65 63 74 6F 72 3B 78 70 01 70>, common:ComponentCommon(inputs:{}, streams:{default=StreamInfo(output_fields:[word], direct:false)}, parallelism_hint:1)) 
 Resource : CPU Pcore Percent set to default 10.0
17:20:24.303 [main] INFO  o.a.storm.security.auth.AuthUtils - Got AutoCreds []
17:20:24.311 [main] DEBUG o.a.s.u.StormBoundedExponentialBackoffRetry - The baseSleepTimeMs [2000] the maxSleepTimeMs [60000] the maxRetries [5]
17:20:24.316 [main] DEBUG o.a.s.s.auth.SimpleTransportPlugin - Simple client transport has been established
17:20:24.341 [main] WARN  org.apache.storm.utils.NimbusClient - Ignoring exception while trying to get leader nimbus info from localhost. will retry with a different seed host.
org.apache.storm.thrift.protocol.TProtocolException: Required field 'nimbuses' is unset! Struct:ClusterSummary(supervisors:[SupervisorSummary(host:localhost, uptime_secs:7, num_workers:4, num_used_workers:0, supervisor_id:64a52cb4-d7dc-4069-af58-705e987b925d, version:VERSION_NOT_PROVIDED)], nimbus_uptime_secs:16, topologies:[], nimbuses:null)
	at org.apache.storm.generated.ClusterSummary.validate(ClusterSummary.java:622) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:735) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.ClusterSummary$ClusterSummaryStandardScheme.read(ClusterSummary.java:652) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.ClusterSummary.read(ClusterSummary.java:566) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:36046) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$getClusterInfo_result$getClusterInfo_resultStandardScheme.read(Nimbus.java:36031) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$getClusterInfo_result.read(Nimbus.java:35970) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.thrift.TServiceClient.receiveBase(TServiceClient.java:86) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$Client.recv_getClusterInfo(Nimbus.java:1156) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.generated.Nimbus$Client.getClusterInfo(Nimbus.java:1144) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:67) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311) [storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157) [storm-core-1.0.2.jar:1.0.2]
	at PersistentWordCount.main(PersistentWordCount.java:60) [lib4/:na]
Exception in thread "main" org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)
	at PersistentWordCount.main(PersistentWordCount.java:60)






i am also getting same error any soln plz tell me

**Comment by KasperMadsen** [comment]
Please post your config file :)

**Comment by swapnilkumbhar1602** [comment]
storm.zookeeper.servers:
 - "xx.xx.xx.1"
storm.zookeeper.port: "2181"
 nimbus.host: "xx.xx.xx.x2"
storm.local.dir: "/home/tapac/apache-storm-0.9.4/data"
#storm.log.dir: "/home/tapac/apache-storm-0.9.4/logs2"
supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703

**Comment by swapnilkumbhar1602** [comment]
storm.zookeeper.servers:
 - "xx.xxx.xx.1"
#storm.zookeeper.port: "2181"
nimbus.host: "xx.xx.xx.2"
storm.local.dir: "/home/tapac/apache-storm-0.9.4/data"
#storm.log.dir: "/home/tapac/apache-storm-0.9.4/logs2"
supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703
nimbus.seeds : [nimbus ip addr]

**Comment by KasperMadsen** [comment]
I mean the config file to the storm-deploy-alternative tool :)

**Comment by swapnilkumbhar1602** [comment]
this is my config file storm.yaml



storm.zookeeper.servers:
 - "xx.xx.xx.1"
#storm.zookeeper.port: "2181"
nimbus.host: "xx.xx.xx.2"
storm.local.dir: "/home/admin/apache-storm-0.9.4/data"
#storm.log.dir: "/home/admin/apache-storm-0.9.4/logs2"
supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703

**Comment by swapnilkumbhar1602** [comment]
i am trying to integrate storm-hbase and getting that error

**Comment by KasperMadsen** [comment]
You have a file in the path: storm-deploy-alternative/conf/configuration.yaml
Please post the content of that file. I can only help you solve problems related to this deployment tool.

**Comment by swapnilkumbhar1602** [comment]
i am not using that storm-deployment tool. i dont have such path and conf  file
i am new to storm

**Comment by KasperMadsen** [comment]
You have raised an issue for a tool, which you do not use, and expect me to help solve a problem with another tool. You should ask your questions in the right forum (Storm) :)

**Comment by swapnilkumbhar1602** [comment]
i am not using that storm-deployment tool. i dont have such path and conf
 file
i am new to storm.

**Comment by swapnilkumbhar1602** [comment]
org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.ui.core$nimbus_summary.invoke(core.clj:389)
	at org.apache.storm.ui.core$fn__12596.invoke(core.clj:938)
	at org.apache.storm.shade.compojure.core$make_route$fn__4631.invoke(core.clj:100)
	at org.apache.storm.shade.compojure.core$if_route$fn__4619.invoke(core.clj:46)
	at org.apache.storm.shade.compojure.core$if_method$fn__4612.invoke(core.clj:31)
	at org.apache.storm.shade.compojure.core$routing$fn__4637.invoke(core.clj:113)
	at clojure.core$some.invoke(core.clj:2570)
	at org.apache.storm.shade.compojure.core$routing.doInvoke(core.clj:113)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at org.apache.storm.shade.compojure.core$routes$fn__4641.invoke(core.clj:118)
	at org.apache.storm.shade.ring.middleware.json$wrap_json_params$fn__12065.invoke(json.clj:56)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__5766.invoke(multipart_params.clj:118)
	at org.apache.storm.shade.ring.middleware.reload$wrap_reload$fn__11217.invoke(reload.clj:22)
	at org.apache.storm.ui.helpers$requests_middleware$fn__6019.invoke(helpers.clj:50)
	at org.apache.storm.ui.core$catch_errors$fn__12786.invoke(core.clj:1225)
	at org.apache.storm.shade.ring.middleware.keyword_params$wrap_keyword_params$fn__5686.invoke(keyword_params.clj:35)
	at org.apache.storm.shade.ring.middleware.nested_params$wrap_nested_params$fn__5729.invoke(nested_params.clj:84)
	at org.apache.storm.shade.ring.middleware.params$wrap_params$fn__5658.invoke(params.clj:64)
	at org.apache.storm.shade.ring.middleware.multipart_params$wrap_multipart_params$fn__5766.invoke(multipart_params.clj:118)
	at org.apache.storm.shade.ring.middleware.flash$wrap_flash$fn__5981.invoke(flash.clj:35)
	at org.apache.storm.shade.ring.middleware.session$wrap_session$fn__5967.invoke(session.clj:98)
	at org.apache.storm.shade.ring.util.servlet$make_service_method$fn__5516.invoke(servlet.clj:127)
	at org.apache.storm.shade.ring.util.servlet$servlet$fn__5520.invoke(servlet.clj:136)
	at org.apache.storm.shade.ring.util.servlet.proxy$javax.servlet.http.HttpServlet$ff19274a.service(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at org.apache.storm.logging.filters.AccessLoggingFilter.handle(AccessLoggingFilter.java:47)
	at org.apache.storm.logging.filters.AccessLoggingFilter.doFilter(AccessLoggingFilter.java:39)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at org.apache.storm.ui.helpers$x_frame_options_filter_handler$fn__6112.invoke(helpers.clj:189)
	at org.apache.storm.ui.helpers.proxy$java.lang.Object$Filter$abec9a8f.doFilter(Unknown Source)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:247)
	at org.apache.storm.shade.org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:210)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.apache.storm.shade.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.apache.storm.shade.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.apache.storm.shade.org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.apache.storm.shade.org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.apache.storm.shade.org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.apache.storm.shade.org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.apache.storm.shade.org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.apache.storm.shade.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

**Comment by swapnilkumbhar1602** [comment]
this is my storm.yaml


storm.zookeeper.servers:
 - "localhost"
nimbus.seeds: ["localhost"]
storm.local.dir: “/home/tapac/apache-storm-1.0.2/data”
nimbus.host: "localhost"
supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703

**Comment by swapnilkumbhar1602** [comment]
this is my storm.yaml


storm.zookeeper.servers:
 - "localhost"

nimbus.seeds: ["localhost"]

storm.local.dir: “/home/tapac/apache-storm-1.0.2/data”

nimbus.host:    "localhost

supervisor.slots.ports:
 - 6700
 - 6701
 - 6702
 - 6703

**Comment by xiaodin1** [comment]
your's config is work well?uper?

**Comment by swapnilkumbhar1602** [comment]
no

**Comment by ndtreviv** [comment]
Gents, Kasper is being very polite.

Your issue is not related to the storm-deploy-alternative project, you've posted it in the wrong place.
Please post it on stackoverflow.com where you will get greater visibility and more help. This issue will be closed unless you can prove that it was created by storm-deploy-alternative. 

Given that you've already said you're not using storm-deploy-alternative then it appears that it is not.

Good luck!
