### ISSUE TITLE
error with getDaemonsToNodeIds function

### ISSUE THREAD

**Issue by aginpatrick** [KasperMadsen/storm-deploy-alternative#48]
Hello,
I'm trying to deploy my storm cluster (mycluster) with your alternative. Result:

    ...
    14051 [main] INFO dk.kaspergsm.stormdeploy.commands.Deploy - Deploying cluster: mycluster Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    	at java.lang.String.substring(String.java:1967)
    	at dk.kaspergsm.stormdeploy.userprovided.Configuration.getDaemonsToNodeIds(Configuration.java:243)
    	at dk.kaspergsm.stormdeploy.commands.Deploy.startNodesNow(Deploy.java:180)
    	at dk.kaspergsm.stormdeploy.commands.Deploy.deploy(Deploy.java:59)
    	at dk.kaspergsm.stormdeploy.StormDeployAlternative.main(StormDeployAlternative.java:81)

My configuration.yaml file is:
    #
    # Amazon EC2 example cluster configuration
    #
    mycluster:
        - image "us-east-1/ami-bdc390aa"            # Ubuntu 14.04 LTS AMI
        - region "us-east-1"                                        # Region
        - t2.micro {ZK, WORKER, MASTER, UI} # Request service
        - t2.micro {ZK, WORKER}                             # Request service
        - t2.micro {ZK, WORKER}                             # Request service
        - t2.micro {WORKER}                                 # Request service
        - remote-exec-preconfig {cd ~, echo hey > hey.txt}
        - remote-exec-postconfig {}
        - security-group "{...my sg-group...}"
        - ssh-key-name "ec2"           # Optional. defaults to "id_rsa"
        - storm-deploy-alternative-cloud-jar-url "https://s3.amazonaws.com/my-storm-deploy-    alternative/storm-deploy-alternative-cloud.jar"
        - storm-tar-gz-url "http://mirror.yannic-bonenberger.com/apache/storm/apache-storm-0.9.3/apache-    storm-0.9.3.tar.gz" # https://storm.apache.org/downloads.html
        - zk-tar-gz-url "http://apache.lauf-forum.at/zookeeper/zookeeper-3.4.7/zookeeper-3.4.7.tar.gz" # https://www.apache.org/dyn/closer.cgi/zookeeper/

Do you have an idea why I get this error?
Regards,
Patrick

**Comment by KasperMadsen** [comment]
Hi Patrick,
Your configurationfile is has configurations which I have not seen before, such as "storm-deploy-alternative-cloud-jar-url"... it seems to indicate you are not using the "master" version of storm-deploy-alternative. If that is true, please test using the current "master" version and see whether your problem is solved. Thx.

**Comment by aginpatrick** [comment]
Hi Kasper, 
Sorry I didn't realize that it was not the master version. After reading the blog <a href="http://knowm.org/how-to-deploy-an-apache-storm-cluster-to-the-amazon-elastic-compute-cloud-ec2/">How to Deploy an Apache Storm Cluster to the Amazon Elastic Compute Cloud (EC2)
</a>, I git-cloned the <a href="https://github.com/timmolter/storm-deploy-alternative">storm-deploy-alternative</a> project from Tim Molter without realizing that it's a fork from your own project. I'll test with your version to see if the problem is solved or not. Thanks again.
